name: Defang

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: Deploy action
        required: true
        default: up
        type: choice
        options:
          - up
          - down

jobs:
  defang:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Deploy with Defang
        uses: DefangLabs/defang-github-action@v1
        with:
          command: ${{ github.event.inputs.action || 'up' }}
          project: geniusgen
          compose-files: docker-compose.yml

      - name: Deployment Summary
        uses: DefangLabs/defang-github-action@v1
        with:
          command: services
          project: geniusgen
